Repository Poketnans/sume-free-share, pull requests merged in 2022-04, with the labels that each got.

#52 fix: user now is created with image
  assets/default.png
  src/routes/userRoutes.ts
  src/services/users/userCreate.service.ts
  src/types/user/userCreate.interface.ts
Labels: review #1

#60 feat: create review implemented
  src/controllers/Review/createReview.ts
  src/repositories/courseReview/courseReview.repository.ts
  src/routes/reviewsRoutes.ts
  src/schemas/index.ts
  src/schemas/reviewSchema.ts
Labels: review #1, review #2

#61 docs: adds user register route docs
  src/docs/swagger.json
Labels: documentation, review #1

#66 fix: setted nullable:false where i judged it needed
  src/entities/Course.ts
  src/entities/CourseReview.ts
  src/entities/Follower.ts
  src/entities/Project.ts
  src/entities/User.ts
  src/migrations/1651066862971-nullablesSetted.ts
Labels: review #1

#64 feat: create project created
  src/controllers/projects/create.project.controller.ts
  src/controllers/projects/index.ts
  src/repositories/category/category.repository.ts
  src/repositories/category/interfaces.ts
  src/repositories/project/interfaces.ts
  src/repositories/project/project.repository.ts
  src/repositories/user/user.repository.ts
  src/routes/projectsRoutes.ts
  src/schemas/create.project.schema.ts
  src/schemas/index.ts
  src/services/projects/create.project.service.ts
  src/services/projects/index.ts
Labels: to refactor

#62 feat: finish update review
  src/controllers/Course/usersCourseGetAll.controller.ts
  src/controllers/Review/index.ts
  src/controllers/Review/updateReview.controllers.ts
  src/middlewares/index.ts
  src/middlewares/validatePermissionReview.middleware.ts
  src/repositories/courseReview/courseReview.repository.ts
  src/repositories/courseReview/interfaces.ts
  src/routes/reviewsRoutes.ts
  src/schemas/index.ts
  src/schemas/userReviewUpdateSchema.ts
  src/services/Review/index.ts
  src/services/Review/updateReview.services.ts
Labels: review #1

#68 feature: swager for update user created
  src/docs/swagger.json
Labels: review #1

#74 feat: image upload doc
  src/docs/swagger.json
Labels: review #1

#85 Docs: login and review
  src/docs/swagger.json
  src/routes/userRoutes.ts
Labels: review #1

#87 Fix/routes course middleware auth
  src/entities/Course.ts
  src/entities/CourseReview.ts
  src/middlewares/course.owner.verifyer.middleware.ts
  src/middlewares/index.ts
  src/repositories/course/course.repository.ts
  src/repositories/course/interfaces.ts
  src/routes/coursesRoutes.ts
  src/services/courses/getOne.services.ts
  src/services/courses/update.services.ts
Labels: review #1
